services:
  cmc-api:
    image: oikos/cmc-api:latest
    build: .
    container_name: oikos-cmc-api
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      MODEL_HELPER_ADDRESS: ${MODEL_HELPER_ADDRESS}
      TOKEN_ADDRESS: ${TOKEN_ADDRESS}
      RPC_URL: ${RPC_URL}
      POOL_ADDRESS: ${POOL_ADDRESS}
      VAULT_ADDRESS: ${VAULT_ADDRESS}
